// <auto-generated />
using System;
using BE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250416132051_AddFilesSupport")]
    partial class AddFilesSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Context.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Brand = "Toyota",
                            Color = "White",
                            Model = "Sedan",
                            Name = "Corolla",
                            Price = 20000,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Brand = "Honda",
                            Color = "Black",
                            Model = "Sedan",
                            Name = "Civic",
                            Price = 22000,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Brand = "Tesla",
                            Color = "Red",
                            Model = "Electric",
                            Name = "Model 3",
                            Price = 35000,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Brand = "Ford",
                            Color = "Blue",
                            Model = "Coupe",
                            Name = "Mustang",
                            Price = 40000,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Brand = "Toyota",
                            Color = "Silver",
                            Model = "Sedan",
                            Name = "Camry",
                            Price = 25000,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Brand = "BMW",
                            Color = "Black",
                            Model = "SUV",
                            Name = "X5",
                            Price = 55000,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Brand = "Audi",
                            Color = "Gray",
                            Model = "Sedan",
                            Name = "A4",
                            Price = 30000,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Brand = "Jeep",
                            Color = "Green",
                            Model = "SUV",
                            Name = "Wrangler",
                            Price = 45000,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Brand = "Honda",
                            Color = "White",
                            Model = "Sedan",
                            Name = "Accord",
                            Price = 27000,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Brand = "Ford",
                            Color = "Blue",
                            Model = "Truck",
                            Name = "Ranger",
                            Price = 32000,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("BE.Context.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
